import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Playfair_Display } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-montserrat" });

const playfair = Playfair_Display({ subsets: ["latin"], variable: "--font-playfair" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("min-h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", montserrat.variable, playfair.variable)}
    >
      <body className="min-h-screen w-full">{children}</body>
    </html>
  );
}
